  
#编译php 
- name: Build configure script.
  command: >
    {{ php_source_configure_command }}
    chdir={{ SOURCE_DIR }}/php-{{ PHP_VER }}
#安装php

- name: 检查php是否被安装
  stat: 
    path: "{{ PHP_DIR }}/bin"
  register: php_install_result


- name: 安装php
  shell: "cd {{ SOURCE_DIR }}/php-{{ PHP_VER }} && make -j 2 && make -j 2 install"
  when: not php_install_result.stat.exists

- name: 创建php-fpm配置目录
  file: name={{ PHP_DIR }}/etc state=directory owner={{ PHP_USER }} group={{ PHP_USER }} mode=0755 recurse=yes

- name: 修改php-fpm配置_1
  shell: "cd {{ SOURCE_DIR }}/php-{{ PHP_VER }} && cp php.ini-production  {{ PHP_DIR }}/etc/php.ini"
  when: not php_install_result.stat.exists


- name: 修改php-fpm配置_2
  lineinfile:
    dest: "{{ PHP_DIR }}/etc/php.ini"
    regexp: "post_max_size = 8M"
    line: "post_max_size = 16M"

- name: 修改php-fpm配置_3
  lineinfile:
    dest: "{{ PHP_DIR }}/etc/php.ini"
    regexp: "max_execution_time = 30"
    line: "max_execution_time = 300"

- name: 修改php-fpm配置_4
  lineinfile:
    dest: "{{ PHP_DIR }}/etc/php.ini"
    regexp: "max_input_time = 60"
    line: "max_input_time = 300"
  
- name: 修改php-fpm配置_5
  lineinfile:
    dest: "{{ PHP_DIR }}/etc/php.ini"
    regexp: ";date.timezone ="
    line: "date.timezone = Asia/Shanghai"

#复制systemctl的启动文件
- name: 拷贝复制systemctl的启动文件
  template: 
    src: php-fpm.j2 
    dest: /usr/lib/systemd/system/php-fpm.service 
    mode: u=rwx,g=rx,o=rx
#复制php主配置文件
- name: 拷贝php主配置文件
  template: src=php-fpm.conf.j2 dest={{ PHP_DIR }}/etc/php-fpm.conf owner={{ PHP_USER }} group={{ PHP_USER }}

#编译安装模块
- include_tasks: install_module.yml
  when: not php_install_result.stat.exists

#重新加载systemctl文件,并设置php-fpm开始启动
- name: systemctl daemon-reload
  shell: "systemctl daemon-reload  && systemctl start php-fpm  &&  systemctl enable php-fpm"

