- name: install master
  hosts: node01
  roles:
  - { role: cdsb.mysql, mysql57_replication_role: 'master',mysql57_install_from_source: true}

- name: install slave
  hosts: node02
  roles:
  - { role: cdsb.mysql, mysql57_port: 3306, mysql57_replication_role: 'slave', mysql57_replication_master: '192.168.0.214',mysql57_install_from_source: true}
